import { Poppins } from "next/font/google";
import "./globals.css";

const inter = Poppins({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="prefetch"
          href="./images/blank.webp"
          as="image"
          crossOrigin="anonymous"
        ></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
